#!/bin/bash
#this the the reisu installer
apt update -y
apt upgrade -y
apt install gcc git make binutils wget vim

cd /tmp
git clone https://github.com/SciresM/hactool
cd hactool
mv config.mk.template config.mk
make
mv hactool /usr/bin
cd ..
git clone https://github.com/The-4n/hacPack
rm -rf hactool

cd hacPack
mv config.mk.template config.mk
make
mv hacpack /usr/bin
cd ..
rm -rf hacPack

wget -O hac2l https://github.com/Adityabyahut/shitmux_nsp_up/raw/main/hac2l
mv hac2l /usr/bin
chmod +x /usr/bin/hac2l
wget -O reisu https://raw.githubusercontent.com/Adityabyahut/shitmux_nsp_up/main/reisu
mv reisu /usr/bin
chmod +x /usr/bin/reisu
wget -O reisu_up https://raw.githubusercontent.com/Adityabyahut/shitmux_nsp_up/main/reisu_up
mv reisu_up /usr/bin
chmod +x /usr/bin/reisu_up
clear

echo "done now exit termux properly"
echo "put your NSP and Keys to -"
echo "Internal_Storage/termux (/storage/emulated/0/termux)"
echo "and run reisu"
echo ""
echo "credits - hactool/hac2l, hacpack"
echo "JeezDisReez, Koki Kurosaki, Rei.."
