#!/bin/bash

cd /tmp
rm -rf /usr/bin/reisu
wget -O reisu https://raw.githubusercontent.com/Adityabyahut/shitmux_nsp_up/main/reisu
mv reisu /usr/bin
chmod +x /usr/bin/reisu
wget -O reisu_up https://raw.githubusercontent.com/Adityabyahut/shitmux_nsp_up/main/reisu_up
mv reisu_up /usr/bin
chmod +x /usr/bin/reisu_up

clear
echo "version 1.0 installed"
echo 'Done'
